name: bible_app
description: ""
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  clipboard: ^0.1.3
  collection: ^1.18.0
  dartz: ^0.10.1
  dynamic_color: ^1.7.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  scrollable_positioned_list: ^0.3.8
  share_plus: ^10.0.2
  shared_preferences: ^2.3.2
  scroll_to_index: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  custom_lint: ^0.6.5
  riverpod_lint: ^2.3.12

flutter:
  uses-material-design: true
  assets:
    - assets/
